name: Weekly
on:
  workflow_dispatch:
  schedule:
  - cron: '0 17 * * MON'

jobs:
  create_issue:
    name: Create weekly
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create weekly
        run: |
          if [[ $CLOSE_PREVIOUS == true ]]; then
            previous_issue_number=$(gh issue list \
              --label "$LABELS" \
              --json number \
              --jq '.[0].number')
            if [[ -n $previous_issue_number ]]; then
              gh issue close "$previous_issue_number"
              gh issue unpin "$previous_issue_number"
            fi
          fi
          new_issue_url=$(gh issue create \
            --title "$TITLE" \
            --assignee "$ASSIGNEES" \
            --label "$LABELS" \
            --body "$BODY")
          if [[ $PINNED == true ]]; then
            gh issue pin "$new_issue_url"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Weekly Sync
          ASSIGNEES: marstamm
          LABELS: weekly
          BODY: |
            ### Agenda

            * [ ] Last week in five minutes (progress, impediments, learnings)
              * [ ] Include review of [our taskboard](https://github.com/orgs/camunda/projects/136) (is your work reflected correctly?)
            * [ ] Review [product-hub](https://github.com/orgs/camunda/projects/9/views/92)
              * [ ] Review Timeline and confidence
            * [ ] Review [retro action items](https://github.com/bpmn-io/rpa-runtime/issues?q=is%3Aopen+is%3Aissue+label%3Aretrospective)
            * [ ] Team member availability: [Upcoming Holidays anyone?](https://app.hibob.com/time-off/peoples-time-off/calendar)

            ### Last week in 5 Minutes

            _Everyone adds a summary of their weeks work here._

            <!--
            #### @username

            ##### Last week

            *
            *

            ##### Next

            *
            -->


            ### Additional Topics

            _Everyone can add topics to this section._
          PINNED: false
          CLOSE_PREVIOUS: true

